name: 'Slack Notify Action'
description: 'Send a slack message using an external service'
inputs:
  github-token:
    description: github access token
    required: false
    default: ${{ github.token }}
  service-url:
    description: external service url
    required: true
  message-type:
    description: slack message type slack_direct_message, slack_channel, or email
    required: true
  message-body:
    description: slack message body
    required: true
  slack-recipient-type:
    description: slack recipient github user type, action-login, github-user, aws-user, slack-channel, slack-user, email
    required: true
  slack-recipient-name:
    description: slack recipient user name, acion-login can be env.GITHUB_ACTOR, comment.user.login, sender.user.login, issue.user.login
    required: true
  blocks:
    description: Slack json structure, see https://api.slack.com/reference/block-kit/blocks
    required: false
  icon-emoji:
    description: Slack icon to display with Slack message
    required: false
  bot-user-name:
    description:  Bot name to display with message
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
